# Cluster Configuration
cluster.name: sophra-es-cluster
node.name: ${HOSTNAME}

# Network Configuration
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery Configuration
discovery.seed_hosts: ["es01", "es02", "es03"]
cluster.initial_master_nodes: ["es01", "es02", "es03"]

# Security Configuration
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certs/transport/${HOSTNAME}/${HOSTNAME}.key
xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certs/transport/${HOSTNAME}/${HOSTNAME}.crt
xpack.security.transport.ssl.certificate_authorities: ["/usr/share/elasticsearch/config/certs/ca/ca.crt"]

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.verification_mode: certificate
xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certs/http/${HOSTNAME}/${HOSTNAME}.key
xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certs/http/${HOSTNAME}/${HOSTNAME}.crt
xpack.security.http.ssl.certificate_authorities: ["/usr/share/elasticsearch/config/certs/ca/ca.crt"]

# Built-in Users Configuration
xpack.security.authc.reserved.enabled: true
xpack.security.authc.realms.native.native1.order: 0

# Memory Configuration
bootstrap.memory_lock: false
node.store.allow_mmap: false

# Node Configuration
node.roles: [ master, data, ingest ]

# Monitoring
xpack.monitoring.collection.enabled: true
