export enum SignalType {
  SEARCH = "SEARCH",
  PERFORMANCE = "PERFORMANCE",
  USER_BEHAVIOR_IMPRESSION = "USER_BEHAVIOR_IMPRESSION",
  USER_BEHAVIOR_VIEW = "USER_BEHAVIOR_VIEW",
  USER_BEHAVIOR_CLICK = "USER_BEHAVIOR_CLICK",
  USER_BEHAVIOR_CONVERSION = "USER_BEHAVIOR_CONVERSION",
  MODEL_PERFORMANCE = "MODEL_PERFORMANCE",
  FEEDBACK = "FEEDBACK",
  SYSTEM_HEALTH = "SYSTEM_HEALTH",
}

export enum EngagementType {
  IMPRESSION = "IMPRESSION",
  VIEW = "VIEW",
  CLICK = "CLICK",
  CONVERSION = "CONVERSION",
}
