name: Testing and Coverage

on:
  push:
    branches:
      - main
      - dev
      - dev-*
  pull_request:
    branches:
      - main
      - dev
      - dev-*

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run tests with coverage
      id: tests
      continue-on-error: true
      run: |
        pnpm test
        ls ./coverage  # Debug: verify coverage files exist after tests

    - name: Upload coverage reports to Codecov
      if: always()
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: sophra-org/sophra

    - name: Upload test results to Codecov
      if: always()
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: test-report.junit.xml

    - name: Check test status
      if: steps.tests.outcome == 'failure'
      run: exit 1

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }} 