name: Test Coverage

on:
  push:
    branches: [main, dev-*]
  pull_request:
    branches: [main, dev-*]

jobs:
  test:
    runs-on: windows-latest

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Get pnpm store directory
        shell: pwsh
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $env:GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Run tests with coverage
        run: pnpm test

      - name: Upload coverage to Codecov
        if: always() && !cancelled()
        continue-on-error: true
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info,./coverage/coverage-final.json,./coverage/cobertura-coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
          directory: ./coverage/
          root_dir: .
          working-directory: .
          dry_run: false

      - name: Upload test results to Codecov
        if: always() && !cancelled()
        continue-on-error: true
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to DeepSource
        if: always() && !cancelled()
        continue-on-error: true
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/lcov.info
